### ISSUE TITLE
It's dark again

### ISSUE THREAD

**Issue by tico-tico** [gluons/NoGithubDarkMode-Firefox#3]
Login to GH, open this url https://github.com/stars?direction=desc&sort=updated

Thanks.

**Comment by gluons** [comment]
Seem that this page actually has the different navigator menu.

If I change it, it may affect [Features](https://github.com/features), [Business](https://github.com/business), [Explore](https://github.com/explore), [Marketplace](https://github.com/marketplace) and [Pricing](https://github.com/pricing).
**Is it OK ❓**

I will find the way.

**Comment by tico-tico** [comment]
You mean if it's OK to make it white everywhere? Well, for me it would be great.

**Comment by gluons** [comment]
OK. It may be an option. I will do it if I'm free. Thank you.

**Comment by gluons** [comment]
@tico-tico Version 1.0.0 has been released. You can try it.

**Comment by tico-tico** [comment]
> Drop support for Firefox that's older than 48.

Sorry, can't test. I have to use v45 'coz Mozilla's broken HW acceleration support for my system in the more recent builds.
Thanks anyway, maybe one day I'll try it.

**Comment by gluons** [comment]
Because I use new [`storage.sync`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync) API that might not work in old Firefox.

---

**`storage.local`**
> The storage API is supported in content scripts from version 48.

Bad news. [`storage.local`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local) API also not work in content scripts in Firefox `< 48`. But I can back to `storage.local` for stability in current Firefox stable.
